name: Package and deploy DevDuck Labspace

env:
  DOCKERHUB_REPO: ajeetraina777/devduck-labspace

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Ensure Compose v2.39.3+ is available (includes bug fixes for publishing)
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: v2.39.3

      - name: Enable Docker experimental features
        run: |
          echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
          echo "COMPOSE_EXPERIMENTAL_OCI_REMOTE=true" >> $GITHUB_ENV

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Verify Docker login and repo access
        run: |
          echo "Logged in as: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "Target repository: ${DOCKERHUB_REPO}"

      - name: Publish DevDuck Labspace
        run: |
          # Use the correct development base image
          docker compose -f oci://dockersamples/labspace-content-dev -f .labspace/compose.override.yaml publish ${DOCKERHUB_REPO} --with-env -y
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          COMPOSE_EXPERIMENTAL_OCI_REMOTE: "true"
