name: Build and Push DevDuck Labspace

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Ensure Compose v2.39.3+ is available (includes bug fixes for publishing)
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: v2.39.3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Compose project
        run: |
          docker compose -f oci://dockersamples/labspace-content-dev -f .labspace/compose.override.yaml publish ajeetraina777/devduck-labspace --with-env -y
        env:
          CONTENT_PATH: ${{ github.workspace }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: 🎉 Success
        run: |
          echo "✅ DevDuck Labspace published successfully!"
          echo "🚀 Run with: docker compose -f oci://ajeetraina777/devduck-labspace up"
          echo "🌐 Then visit: http://localhost:3030"
